name = "ComputationManager"
uuid = "5fbd250a-b5cd-4b13-969b-07b3ee66658a"
authors = ["Morten Piibeleht <morten.piibeleht@gmail.com> and contributors"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"

[compat]
DataStructures = "0.18"
IOCapture = "0.2"
julia = "1"

[extras]
IOCapture = "b5f81e59-6552-4d32-b1f0-c071b021bf89"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "IOCapture"]
